package com.chang.ng.phone.data.model;

//Generated 11 Jun, 2015 7:02:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
* Settings generated by hbm2java
*/
@Entity
@Table(name = "settings")
//@Cache(usage = CacheConcurrencyStrategy.READ_WRITE,region="settings")
public class Settings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String keyname;
	private String value;
	private String description;

	public Settings() {
	}

	public Settings(String keyname, String value, String description) {
		this.keyname = keyname;
		this.value = value;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@Column(name = "value", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "keyname", length = 100)
	public String getKeyname() {
		return keyname;
	}

	public void setKeyname(String keyname) {
		this.keyname = keyname;
	}

}